## Numerical Python

In [113]:
import numpy as np

In [114]:
# How fast are numpy array compared to list.
my_arr = np.arange(1_00_000)
my_list = list(range(1_00_000))

In [115]:
%timeit my_arr2 = my_arr*2

53 µs ± 1.22 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [116]:
%timeit my_list2 = my_list*2

830 µs ± 30.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## Numpy ndarray: A multidimensional array object

In [117]:
data = np.array([[1.5,-0.1,3], [0,-3,6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [118]:
data*10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [119]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [120]:
data.shape

(2, 3)

In [121]:
data.dtype

dtype('float64')

In [123]:
#creating array from list
data1 =[6,7.5,8,0,1]

In [124]:
arr = np.array(data1)
arr

array([6. , 7.5, 8. , 0. , 1. ])

In [125]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [126]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [127]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [128]:
np.empty((2,3,4))

array([[[9.81260309e-312, 9.81260312e-312, 9.81260313e-312,
         9.81260316e-312],
        [9.81260314e-312, 9.81260315e-312, 9.81260315e-312,
         9.81260316e-312],
        [9.81260314e-312, 9.81260311e-312, 9.81260365e-312,
         9.81260367e-312]],

       [[9.81260369e-312, 9.81260365e-312, 9.81260369e-312,
         9.81260365e-312],
        [9.81260365e-312, 9.81260365e-312, 9.81260365e-312,
         9.81260365e-312],
        [9.81260365e-312, 9.81260365e-312, 9.81260365e-312,
         9.81260365e-312]]])

In [129]:
np.arange(15) # equivalent to range() 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [130]:
arr1 = np.array(np.arange(10), dtype = np.float64) 
arr1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [131]:
arr2 = np.array(np.arange(10), dtype = np.int64) 
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

## Arithmetic with Numpy Array

In [132]:
arr = np.array([[1,2,3],[4,5,6.0]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [133]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [134]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [135]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [136]:
arr**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [137]:
# Compare with same size array

arr2 = np.array([[0,4,1],[7,2,12.0]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [140]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [141]:
arr>arr2

array([[ True, False,  True],
       [False,  True, False]])

## Indexing and slicing

In [157]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
arr[5]

5

In [144]:
arr[2:5]

array([2, 3, 4])

In [147]:
arr[5:8] = 101 #broadcasting vs list

In [148]:
arr

array([  0,   1,   2,   3,   4, 101, 101, 101,   8,   9])

In [149]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [151]:
l[2:5]

[2, 3, 4]

In [152]:
l[2:5] = 100 # error in list

TypeError: can only assign an iterable

In [153]:
l2 = l[2:5]
l2

[2, 3, 4]

In [154]:
l2[2] = 100
l2

[2, 3, 100]

In [155]:
l # remain same 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [159]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
arr_sub = arr[5:8]
arr_sub

array([5, 6, 7])

In [162]:
arr_sub[2] = 1000
arr_sub

array([   5,    6, 1000])

In [164]:
arr

array([   0,    1,    2,    3,    4,    5,    6, 1000,    8,    9])

In [165]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [167]:
arr2d[2]

array([7, 8, 9])

In [168]:
arr2d[0][2]

3

In [169]:
arr2d[0,2]

3

In [170]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d #2X2X3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [172]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [173]:
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [174]:
arr3d[0] = 100
arr3d

array([[[100, 100, 100],
        [100, 100, 100]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [175]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [176]:
arr3d[1,0]

array([7, 8, 9])

In [177]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [178]:
arr2d[:2] # select the first two rows 

array([[1, 2, 3],
       [4, 5, 6]])

In [179]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [180]:
arr2d[1, :2]

array([4, 5])

In [181]:
arr2d[2]

array([7, 8, 9])

In [182]:
arr2d[1,:2]

array([4, 5])

## Boolean Indexing

In [183]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

In [184]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [185]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [186]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [188]:
data[names =='Bob']

array([[4, 7],
       [0, 0]])

In [189]:
data[~(names=='Bob')]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [190]:
data[data<0]

array([ -5, -12,  -4])

In [191]:
data[data<0]=0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

## Fancing Indexing

In [192]:
arr = np.zeros((8,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [193]:
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [195]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [196]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

## Transposing and Swapping Axes

In [197]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [198]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [199]:
# dot
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [200]:
arr.T @ arr

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

## Pseudorandom Number Generation

In [201]:
# numpy.random

sample = np.random.standard_normal(size = (4,4))
sample

array([[-1.25013073,  0.60054056,  0.96423965,  0.61367103],
       [ 1.29005069,  1.05954584, -0.39338143, -2.22701404],
       [-0.30617444,  0.41698426,  0.70516326, -0.79636009],
       [-1.44986153,  0.9944713 , -1.3817924 , -0.102078  ]])

In [202]:
from random import normalvariate
N = 1_000_000
%timeit [normalvariate(0,1) for x in range(N)]

788 ms ± 38.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [203]:
%timeit np.random.standard_normal(N)

20.4 ms ± 1.83 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [204]:
rng = np.random.default_rng(seed = 12345)
rng

Generator(PCG64) at 0x1CE6BCE2180

In [205]:
data = rng.standard_normal((2,3))
data

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465]])

## Universal Functions: Fast element-wise Array Functions

In [206]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [208]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [101]:
np.exp(arr)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06]])

In [209]:
x = rng.standard_normal(8)
y = rng.standard_normal(8)

In [210]:
x

array([-1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306,  2.34740965,
        0.96849691, -0.75938718,  0.90219827])

In [211]:
y

array([-0.46695317, -0.06068952,  0.78884434, -1.25666813,  0.57585751,
        1.39897899,  1.32229806, -0.29969852])

In [212]:
np.maximum(x,y)

array([-0.46695317,  0.6488928 ,  0.78884434, -1.25666813,  2.34740965,
        1.39897899,  1.32229806,  0.90219827])

In [213]:
x*100

array([-136.77927018,   64.88928022,   36.10581131, -195.2863063 ,
        234.74096544,   96.84969058,  -75.93871804,   90.21982742])

In [214]:
remainder, whole_part = np.modf(x)

In [215]:
remainder

array([-0.3677927 ,  0.6488928 ,  0.36105811, -0.95286306,  0.34740965,
        0.96849691, -0.75938718,  0.90219827])

In [216]:
whole_part


array([-1.,  0.,  0., -1.,  2.,  0., -0.,  0.])